[package]
name = "libva-x264"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
c_string = "0.7.2"

[build-dependencies]
bindgen = "0.66.1"


